#!/usr/bin/env python3

import time
import sys

with open(sys.argv[1], 'r') as fp:
    while True:
        line = fp.readline()
        if not line:
            break
        print(line, end='')
        time.sleep(.02)
